name: Release Server
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Release Tags'

jobs:
    update_server:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASS }}
            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                context: .
                file: ./docker/Dockerfile-server
                push: true
                tags: beclab/settings-server:${{ github.event.inputs.tags }}
                platforms: linux/amd64,linux/arm64
