name: Release Profile Preview
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Release Tags'
  push:
    branches:
       - "main"
    tags:
      - "v*"

jobs:
  release_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: get latest tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        id: get-latest-tag
        
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "18.15"
      - name: Install
        run: npm i -g @quasar/cli
      - name: Build
        run: npm install;npm run editor:build-preview
      - name: Build and push
        uses: docker/build-push-action@v3
        env:
          TAG: ${{ steps.get-latest-tag.outputs.tag || github.event.inputs.tags || 'latest'}} 
        with:
          context: .
          file: ./docker/profile/Dockerfile-profile-preview
          push: true
          tags: beclab/profile-preview:${{env.TAG}}
          platforms: linux/amd64,linux/arm64
